export const environment = {
    production: true,
    VERSION: 'v1.2.0',
    APP_NAME_TITLE: "Casilla Fiscal Electrónica",
    APP_NAME: "Casilla Fiscal Electrónica",
    ENTITY_NAME: 'Ministerio Público - Fiscalía de la Nación',
    AFILIACION_ENDPOINT: `https://cfe.mpfn.gob.pe/ms-afiliacion-casilla`,
    CASILLA_ENDPOINT: `https://cfe.mpfn.gob.pe/ms-casilla-electronica`,
    DOCUMENTOS_ENPOINT: `https://cfe.mpfn.gob.pe/cfe/generales/documento/v1/cftm/t/gestion/obtienedocumento`, 
    MAESTROS_ENDPOINT: `https://cfe.mpfn.gob.pe/cfe/generales/maestro`,
    CAPTCHA_SITE_KEY: `6LeYCIcnAAAAAAU9CguAytPy7fML2_s1kAD21U8i`,
    HTTP_CASILLA_WEB: `https://cfe.mpfn.gob.pe/casilla-fiscal-electronica`,
    ENCRYPT_KEY: `KRx8zM2x7NDbbdcA`,
    TIME_TO_RESEND_CODE: 120,
    MAX_TIME_2FA: 600,
}